server:
  port: 8081

spring:
  application:
    name: user-auth-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eventzen_users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Aiyan123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt:
  secret: eventzen-shared-secret-key-that-is-at-least-256-bits-long-for-hs256
  expiration: 86400000  # 24 hours in milliseconds

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
