server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: event-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eventzen_events?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Aiyan123@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# JWT Configuration (MUST match Auth Service's secret)
jwt:
  secret: ${JWT_SECRET:your_jwt_secret_at_least_256_bits_long}
  expiration: 86400000

# OpenFeign - Auth Service URL
feign:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Resilience4j Circuit Breaker Config
resilience4j:
  circuitbreaker:
    instances:
      authService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 3

